spring.application.name=backend

spring.datasource.url = jdbc:postgresql://localhost:5432/UpBot
spring.datasource.username = postgres
spring.datasource.password = latakasapna
spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

spring.security.user.name=aryan
spring.security.user.password = aryan123